### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by momendiab**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Please fix:

- only one top cell is allowed
- the phase shifters are applied to the waveguides going into the grating couplers. Note that the detectors cannot measure phase (only intensity) so you will not see any change with applied voltage.  You need some circuit that converts phase into intensity, such as an interferometer.

**Review by lukasc-ubc — CHANGES_REQUESTED** [review]
please fix

**Comment by momendiab** [comment]
Thanks Lukas! 
The top 3 grating couplers are inputs. My understanding is that changing the voltage on one of the heaters will produce a sinusoidal change in intensity in the bottom (output) grating coupler.

**Comment by lukasc-ubc** [comment]
we only have one laser as input.  the other fibers are all detectors.

**Comment by momendiab** [comment]
In that case, we'll have to split the one GC input into 3 ports and phase-shift them relative to each other to see the fringes. The latest layout has 2 circuits. One with heaters and one without.

**Comment by lukasc-ubc** [comment]
Running verification on SiEPIC_Passives_momen_beamCombiner.gds
Traceback (most recent call last):
  File "/home/runner/work/openEBL-2024-02-Si-Heaters/openEBL-2024-02-Si-Heaters/run_verification.py", line 26, in <module>
    top_cell = layout.top_cell()
RuntimeError: The layout has multiple top cells in Layout.top_cell

Also, in this design, the phase shifter won't do anything to the optical spectrum!

**Comment by lukasc-ubc** [comment]
image

**Comment by lukasc-ubc** [comment]
you have M1 and M2 crossing, but in this process these all become short circuits:

image

the way you have the pads is not correct.  The two 2 pads should be for 1 heater, and the bottom 2 for the 2nd heater.


image

**Comment by lukasc-ubc** [comment]
a phase shifter directly connected to a grating coupler doesn't make sense.  Nothing will happen, other than the chip heating up a bit.

image

**Comment by lukasc-ubc** [comment]
there is only one file here. Is that intentional?

**Comment by momendiab** [comment]
> there is only one file here. Is that intentional?

Yes. The other files were older submissions with errors.

**Pull request merged**
