### PR TITLE
GC with lenses on heater run

### PR DESCRIPTION
**Pull request by masihUBC**
Hi Lukas, 
I added 64 layouts for GC with lenses which equivalent to 4 rows in the layout (currently 2 rows is occupied in the left side of the heater chip)  there is a fiber array configuration functional error in klayout that can be waived.

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Please fix: The designs should not have multiple top-cells.

This can be done via the menu item, or via script function:

`from SiEPIC.scripts import delete_extra_topcells
`

image
image

**Comment by lukasc-ubc** [comment]
My script didn't merge your files since there are multiple top cells.  

I can also check for cells named "top", which I just added to the script.

**Comment by masihUBC** [comment]
reuploaded the GCs with lenses and added 2 phase shifter designs

**Comment by lukasc-ubc** [comment]
The merge isn't going to work for some reason.
I think we'll have to close this PR, and you will need to create a new one.

image

**Pull request closed without merging**
