### PR TITLE
Added last heaters file; important labels question

### PR DESCRIPTION
**Pull request by LeelaQ2**
One potential issue about labels: When I downloaded the merged layout and read the corresponding EBeam.txt  file, I saw that the measurement labels were not included for most people's heater layouts in the text file. I followed the instructions on EdX and labeled mine with "opt_TE..." for heaters, which is different from "opt_in_TE..." for passives. But it looks like the labels "opt_in_TE..." got printed in the text file for people who used the apparently wrong convention, while the labels "opt_TE..." didn't get printed for people who used the right convention. Could this cause label recognition issues for measurements?

On a related note: in this EBeam_heaters_LeelaQv6.gds and my heaters_v5 design as well, I have multiple bond pads with the exact same label. This is because the optical input goes to multiple (connected) devices with heaters, so there is not a one-to-one match between optical input and electrical pads. Both heaters will have applied voltage at the same time. Will having 2 pads with the same label be an issue? (Note that the ,unique-device-id> is still used for only one optical input, but for multiple ground pads and multiple signal pads.)

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
opt vs. opt_in in the text file - that should be ok.

pads: let us check and get back to you.

**Comment by omidesml** [comment]
Your layout here looks okay. But, if you are submitting multiple designs, please make sure the labels are unique (optical and electrical) -- unique device IDs across your designs.

**Comment by LeelaQ2** [comment]
> Your layout here looks okay. But, if you are submitting multiple designs, please make sure the labels are unique (optical and electrical) -- unique device IDs across your designs.

Ah, I see, thanks for pointing this out. Let me change the optical input labels on one of my gds files then. Within a gds file, all my optical input labels are unique, but I believe I have the same labels on two different gds files. I will commit a new version and make a pull request shortly.

**Comment by LeelaQ2** [comment]
No changes needed for heater file submissions. Will you please merge EBeam_heaters_LeelaQv6.gds?

(The changes I made were for passive designs in the other folder.)

**Pull request merged**
