### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by p-zavyalova**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
- have phase shifters outside interferometric devices is not useful
- the electrical pads have to be exactly as per the slides, namely 4 pads for 2 heaters.

**Comment by lukasc-ubc** [comment]
@p-zavyalova can you please fix?

**Comment by p-zavyalova** [comment]
As with the layout submitted by Momen Diab, this is meant to be a 3x1 combiner.  The top 3 GCs are inputs so the shifting occurs before combination. It's alright if it cannot be fully tested using the automated setup.

**Comment by omidesml** [comment]
The layout looks fine. Would you please add labels to the electrical pads? 
https://docs.google.com/presentation/d/e/2PACX-1vQGfiCmm46GBsWxrSuZYHMeLCWASdmt2cxjxVpdDSf_kQTqfqs055J6wp7R7IxJ8r288hIqqrP7QlkA/pub?start=false&loop=false&delayms=3000 
slide 37

**Comment by lukasc-ubc** [comment]
we will merge this and fabricate. But please add the labels and resubmit, WITHOUT changing anything else.

**Pull request merged**
